config/routes.rb
Blog::Application.routes.draw do |map|
 root :to => "articles#index"
  resources :articles do
    member do
      post :vote_up
    end
  end
  resources :articles do
    member do
      post :vote_down
    end
  end
  resources :articles do
    member do
      post :notify_friend
    end
    resources :comments
  end
  resources :users
  resource :session
  resources :articles do
    member do
      post 'vote'
    end
  end
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"  
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_voteable
  validates :title, :presence => true
  validates :body, :presence => true
  default_scope order('created_at DESC')
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :votes
  has_many :comments
  has_many :comments, :order => "created_at DESC" 
  scope :published, where("articles.published_at IS NOT NULL")
  scope :draft, where("articles.published_at IS NULL")
  scope :recent, lambda { published.where("articles.published_at > ?", 1.week.ago.to_date)}
  scope :where_title, lambda { |term| where("articles.title LIKE ?", "%#{term}%") }
 
  def long_title
    "#{title} - #{published_at}"
  end
  
  def published?
    published_at.present?
  end
  
  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :notify_friend]

  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all
    @articles = Article.page(params[:page]).per(10)
      respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = current_user.articles.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => t('articles.create_success')) }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = current_user.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => t('articles.update_success')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
  
  def notify_friend
    @article = Article.find(params[:id])
    Notifier.email_friend(@article, params[:name], params[:email]).deliver
    redirect_to @article, :notice => t('articles.notify_friend_success')
  end  

=begin
  def vote_up
    @article = Article.find(params[:id])
    @user = User.find(current_user.id)
    @vote = @article.votes.create(params[:article])
    @vote.user = @user
    @vote.article = @article
    @vote.score = 1
    respond_to do |format|
      if @vote.save!
        format.html {redirect_to(articles_path)}
      else
        format.html {redirect_to(articles_path)}
      end
    end 
  end


  def vote_up
    @article = Article.find(params[:id])
    @user = User.find(current_user.id)
    @vote = @article.votes.create(params[:article])
    @vote.user = @user
    @vote.article = @article
    @vote.score = 1
    @article_votes = 3
    puts article_votes: #{@article_votes}
      begin
        current_user.vote_for(@article = Article.find(params[:id]))
        redirect_to :back
      rescue ActiveRecord::RecordInvalid
        redirect_to :back
      end
  end
=end

   def vote_up
     begin
       @article = Article.find(params[:id])
       @vote = current_user.votes.find_by_voteable_id(@article.id)
       if @vote == nil
       current_user.vote_for(@article = Article.find(params[:id]))
       redirect_to :back
       else
       @vote.delete
       current_user.vote_for(@article = Article.find(params[:id]))
       redirect_to :back
       end
     rescue ActiveRecord::RecordInvalid
     end
   end
   
   def vote_down
      begin
        @article = Article.find(params[:id])
        @vote = current_user.votes.find_by_voteable_id(@article.id)
        if @vote == nil
        current_user.vote_for(@article = Article.find(params[:id]))
        redirect_to :back
        else
        @vote.delete
        current_user.vote_against(@article = Article.find(params[:id]))
        redirect_to :back
        end
#!        render :nothing => true, :status => 200
      rescue ActiveRecord::RecordInvalid
#!  render :nothing => true, :status => 404
      end
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def url_changing(article)
    article.parse(url).host[/(?:www\.)?(.*)/,1]
  end
end

app/views/articles/_article.html.erb
<%= div_for article do %>
  <h3>
    Votes: <%= article.votes_for - article.votes_against %>    
    <%= link_to( image_tag('updark.png'), vote_up_article_path(article), :method => :article)  %>
    <%= link_to( image_tag('downdark.png'), vote_down_article_path(article), :method => :article)  %>
    
<%-#    <%= link_to('Up!', vote_up_article_path(article), :method  => :article) %>
<%-#        <%= link_to('Down!', vote_down_article_path(article), :method  => :article) %>


    <%= link_to article.title, article %>
    <% if article.owned_by? current_user %>
      <span class='actions'>

        <%= link_to t('general.edit'), edit_article_path(article) %>
        <%= link_to t('general.delete'), article, :confirm => t('general.are_you_sure'), :method => :delete %>
      </span>
    <% end %>
  </h3>
  <%= simple_format raw(article.body) %>
<%#  <%= simple_format raw(article.excerpt) %>
  <%= simple_format raw(article.location) %>
  <%= simple_format raw(article.published_at) %>
  <%= link_to article.excerpt, article.excerpt %>

<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
<!--  <div class="field">
    <%= f.label "Categories" %><br />
    <% for category in Category.all %>
      <%= check_box_tag 'article[category_ids][]', category.id, @article.category_ids.include?(category.id), :id => dom_id(category) %>
      <%= label_tag dom_id(category), category.name, :class => "check_box_label" %>
    <% end %>
  </div>-->
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :excerpt, :value => 'http://' %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/articles/_notify_friend.html.erb
<%= form_tag(notify_friend_article_path(@article), :id => 'notify_friend_form', :style => 'display:none') do %>
  <div class="field">
    <%= label_tag :name, t('general.your_name') %><br />
    <%= text_field_tag :name %>
  </div>
  <div class="field">
    <%= label_tag :email, t('general.your_friend_email') %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="actions">
    <%= submit_tag t('general.send_email') %>
    <%= t('general.or') %>
    <%= link_to t('general.cancel'), '#', :onclick => "$('#notify_friend_form').slideUp()" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1><%= t('articles.editing_article') %></h1>

<%= render 'form' %>

<%= link_to t('general.show'), @article %> |
<%= link_to t('general.back'), articles_path %>

app/views/articles/index.html.erb
<h1>
<!--<%= t('articles.listing_articles') %>-->
<%= link_to "Home", root_path %>
<%= link_to "Post Your Own Cup!", new_article_path %>
<%= link_to "Most Popular", new_article_path %>
<%= link_to "FAQ", new_article_path %></h1>
</h1>


<% @articles.each do |article| %>
<!--  <p><%= render article %></p>-->
  <%= render article %>
  <br />
<% end %>

<%= paginate @articles %>
<!--<%= render @articles, :spacer_template => "article_spacer" %>-->

app/views/articles/new.html.erb
<h1>New article
<!--<%= link_to 'Back', articles_path %>--></h1>

<%= render 'form' %>

<!--<%= link_to 'Back', articles_path %>-->

app/views/articles/show.html.erb
<%= render @article %>

<%= link_to t('general.email_a_friend'), '#', :onclick => "$('#notify_friend_form').slideDown()" %>
<%= render 'notify_friend' %>


<h3><%= t('comments.comments') %></h3>
<div id="comments">
  <%= render @article.comments %>
</div>

<%= link_to t('comments.new_comment'), new_article_comment_path(@article, :format => :js), :remote => true, :id => 'new_comment_link' %>